-- Neovim diagnostics interface.
--
-- Converts mplint issues into Neovim diagnostics, publishes them to the
-- editor, and manages clearing diagnostic state.

local M = {}
local ns = vim.api.nvim_create_namespace 'mplint'

---@class MplintIssue An issue object generated by the MetaPost linter backend.
---@field lnum integer The 1-indexed raw line number where the issue was flagged.
---@field severity "'ERROR'"|"'WARN'" The severity category of the logged message.
---@field message string The explicit diagnostic details describing the rule violation.

--- Standardize, bound-check, and send custom linter issues to Neovim's diagnostic engine.
--- This maps 1-indexed linter lines down to 0-indexed API lines and clamps them to the buffer limits.
--- @param bufnr integer The targeted buffer identifier to send diagnostics to.
--- @param issues MplintIssue[] Array list containing raw diagnostic issue logs.
--- @param lines_count integer Total number of lines present in the target buffer (used for clamping).
function M.publish_diagnostics(bufnr, issues, lines_count)
  local final_diagnostics = {}
  for _, issue in ipairs(issues) do
    local max_line = math.max(0, lines_count - 1)
    local lnum = math.min(math.max(0, issue.lnum - 1), max_line)
    table.insert(final_diagnostics, {
      bufnr = bufnr,
      lnum = lnum,
      col = 0,
      severity = issue.severity == 'ERROR' and vim.diagnostic.severity.ERROR or vim.diagnostic.severity.WARN, -- NOTE: maybe change for INFO
      message = issue.message,
      source = 'mplint',
    })
  end
  vim.diagnostic.set(ns, bufnr, final_diagnostics)
end

--- Clear and completely purge all active mplint diagnostic markers from a specific buffer.
--- @param bufnr integer The buffer identifier to wipe clean.
function M.clear(bufnr) vim.diagnostic.reset(ns, bufnr) end

return M
